# Generated by Django 5.2.1 on 2025-05-23 06:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="종류명"),
                ),
                ("slot", models.CharField(max_length=30, verbose_name="장착 부위")),
                ("order", models.IntegerField(default=0, verbose_name="정렬 순서")),
            ],
            options={
                "verbose_name": "아이템 종류",
                "verbose_name_plural": "아이템 종류 목록",
                "db_table": "item_types",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="직업명"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("tank", "탱커"),
                            ("healer", "힐러"),
                            ("melee", "근딜"),
                            ("ranged", "원딜"),
                            ("caster", "캐스터"),
                        ],
                        max_length=10,
                        verbose_name="역할",
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=100, verbose_name="아이콘"),
                ),
            ],
            options={
                "verbose_name": "직업",
                "verbose_name_plural": "직업 목록",
                "db_table": "jobs",
            },
        ),
        migrations.CreateModel(
            name="Raid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="레이드명")),
                ("tier", models.CharField(max_length=20, verbose_name="난이도")),
                ("patch", models.CharField(max_length=10, verbose_name="패치")),
                ("min_ilvl", models.IntegerField(verbose_name="최소 아이템레벨")),
                ("max_ilvl", models.IntegerField(verbose_name="최대 아이템레벨")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "레이드",
                "verbose_name_plural": "레이드 목록",
                "db_table": "raids",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="아이템명")),
                ("item_level", models.IntegerField(verbose_name="아이템레벨")),
                (
                    "floor",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="층",
                    ),
                ),
                (
                    "is_weapon",
                    models.BooleanField(default=False, verbose_name="무기 여부"),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="raids.itemtype",
                        verbose_name="종류",
                    ),
                ),
                (
                    "job_restrictions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="restricted_items",
                        to="raids.job",
                        verbose_name="직업 제한",
                    ),
                ),
                (
                    "raid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="raids.raid",
                        verbose_name="획득처",
                    ),
                ),
            ],
            options={
                "verbose_name": "아이템",
                "verbose_name_plural": "아이템 목록",
                "db_table": "items",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_name",
                    models.CharField(max_length=50, verbose_name="캐릭터명"),
                ),
                (
                    "item_level",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999),
                        ],
                        verbose_name="아이템레벨",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 상태"),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="가입일"),
                ),
                (
                    "job",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="raids.job",
                        verbose_name="직업",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_profiles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "공대원",
                "verbose_name_plural": "공대원 목록",
                "db_table": "players",
            },
        ),
        migrations.CreateModel(
            name="EquipmentSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "set_type",
                    models.CharField(
                        choices=[
                            ("start", "출발 세트"),
                            ("current", "현재 세트"),
                            ("target", "최종 세트"),
                        ],
                        max_length=10,
                        verbose_name="세트 종류",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_sets",
                        to="raids.player",
                        verbose_name="플레이어",
                    ),
                ),
            ],
            options={
                "verbose_name": "장비 세트",
                "verbose_name_plural": "장비 세트 목록",
                "db_table": "equipment_sets",
                "unique_together": {("player", "set_type")},
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="재화명"),
                ),
                (
                    "weekly_limit",
                    models.IntegerField(default=0, verbose_name="주간 제한"),
                ),
                (
                    "raid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currencies",
                        to="raids.raid",
                        verbose_name="관련 레이드",
                    ),
                ),
            ],
            options={
                "verbose_name": "재화",
                "verbose_name_plural": "재화 목록",
                "db_table": "currencies",
            },
        ),
        migrations.CreateModel(
            name="RaidGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="공대명")),
                (
                    "distribution_method",
                    models.CharField(
                        choices=[
                            ("priority", "우선순위 분배"),
                            ("rotation", "먹고 빠지기"),
                        ],
                        default="priority",
                        max_length=20,
                        verbose_name="분배 방식",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 상태"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="led_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="공대장",
                    ),
                ),
                (
                    "raid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="raids.raid",
                        verbose_name="레이드",
                    ),
                ),
            ],
            options={
                "verbose_name": "공대",
                "verbose_name_plural": "공대 목록",
                "db_table": "raid_groups",
            },
        ),
        migrations.AddField(
            model_name="player",
            name="raid_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="raids.raidgroup",
                verbose_name="공대",
            ),
        ),
        migrations.CreateModel(
            name="ItemDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distributed_at", models.DateTimeField(verbose_name="분배일시")),
                ("week_number", models.IntegerField(verbose_name="주차")),
                ("notes", models.TextField(blank=True, verbose_name="메모")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raids.item",
                        verbose_name="아이템",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_items",
                        to="raids.player",
                        verbose_name="획득자",
                    ),
                ),
                (
                    "raid_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributions",
                        to="raids.raidgroup",
                        verbose_name="공대",
                    ),
                ),
            ],
            options={
                "verbose_name": "아이템 분배",
                "verbose_name_plural": "아이템 분배 기록",
                "db_table": "item_distributions",
            },
        ),
        migrations.CreateModel(
            name="RaidSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="일정명")),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "월요일"),
                            (1, "화요일"),
                            (2, "수요일"),
                            (3, "목요일"),
                            (4, "금요일"),
                            (5, "토요일"),
                            (6, "일요일"),
                        ],
                        verbose_name="요일",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="시작 시간")),
                ("end_time", models.TimeField(verbose_name="종료 시간")),
                (
                    "is_recurring",
                    models.BooleanField(default=True, verbose_name="반복 여부"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "raid_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="raids.raidgroup",
                        verbose_name="공대",
                    ),
                ),
            ],
            options={
                "verbose_name": "레이드 일정",
                "verbose_name_plural": "레이드 일정 목록",
                "db_table": "raid_schedules",
                "ordering": ["weekday", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_pentamelded",
                    models.BooleanField(default=False, verbose_name="금단 여부"),
                ),
                (
                    "equipment_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipments",
                        to="raids.equipmentset",
                        verbose_name="장비 세트",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raids.item",
                        verbose_name="아이템",
                    ),
                ),
            ],
            options={
                "verbose_name": "장비",
                "verbose_name_plural": "장비 목록",
                "db_table": "equipments",
                "unique_together": {("equipment_set", "item")},
            },
        ),
        migrations.CreateModel(
            name="CurrencyRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="필요량")),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raids.currency",
                        verbose_name="재화",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currency_requirements",
                        to="raids.item",
                        verbose_name="아이템",
                    ),
                ),
            ],
            options={
                "verbose_name": "재화 요구사항",
                "verbose_name_plural": "재화 요구사항 목록",
                "db_table": "currency_requirements",
                "unique_together": {("item", "currency")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="player",
            unique_together={("user", "raid_group")},
        ),
    ]
