# Generated by Django 5.2.1 on 2025-05-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raids", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={
                "ordering": ["role", "name"],
                "verbose_name": "직업",
                "verbose_name_plural": "직업 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="raid",
            options={
                "ordering": ["id"],
                "verbose_name": "레이드",
                "verbose_name_plural": "레이드 목록",
            },
        ),
        migrations.AlterField(
            model_name="raid",
            name="tier",
            field=models.CharField(max_length=20, verbose_name="단계"),
        ),
    ]
