# Generated by Django 5.2.1 on 2025-05-28 08:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raids", "0002_alter_job_options_alter_raid_options_alter_raid_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="floor",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="층",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="raid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="raids.raid",
                verbose_name="획득처",
            ),
        ),
    ]
